# Generated by Django 2.0.3 on 2018-09-22 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_auto_20180919_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=0)),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_primary', to='product.Product')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_recommendation', to='product.Product')),
            ],
        ),
    ]
