# Generated by Django 2.0.3 on 2018-09-23 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_productrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecommendation',
            name='primary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precommendations', to='product.Product'),
        ),
    ]
