# Generated by Django 2.0.3 on 2019-06-07 00:25

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_auto_20180922_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.MoneyField(currency='MXN', decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=django_prices.models.MoneyField(blank=True, currency='MXN', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=django_prices.models.MoneyField(blank=True, currency='MXN', decimal_places=2, max_digits=12, null=True),
        ),
    ]
