# Generated by Django 2.0.3 on 2019-06-07 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_auto_20190606_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products2', to='product.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products3', to='product.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products4', to='product.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product5', to='product.Category'),
        ),
    ]
