# Generated by Django 2.0.3 on 2018-09-23 03:23

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180922_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='blog-images'),
        ),
    ]
